<?php
session_start(); require __DIR__.'/config/database.php'; require __DIR__.'/includes/helpers.php';
$featured = $pdo->query("SELECT l.*, c.name category_name,COALESCE(ROUND(AVG(r.rating),1),l.rating) AS display_rating FROM locations l JOIN categories c ON c.id=l.category_id LEFT JOIN reviews r ON r.location_id=l.id GROUP BY l.id,c.name ORDER BY display_rating DESC,l.id DESC LIMIT 8")->fetchAll();
$destinations = $pdo->query("SELECT id,name,notes,average_cost,rating,image_url FROM destinations WHERE is_active=1 ORDER BY name LIMIT 8")->fetchAll();
$favoriteIds=[];
if(!empty($_SESSION['user'])){
  $st=$pdo->prepare('SELECT location_id FROM favorites WHERE user_id=?');$st->execute([(int)$_SESSION['user']['id']]);$favoriteIds=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));
}
$pageTitle='Lập kế hoạch chuyến đi'; include __DIR__.'/includes/header.php'; show_flash();
?>
<section class="hero-travel"><div class="hero-inner"><div class="hero-kicker">TRAVEL PLANNER · TRIPMATE</div><h1>Mỗi chuyến đi, một kế hoạch hoàn chỉnh.</h1><p>Khám phá điểm đến, gom địa điểm yêu thích và biến ý tưởng thành lịch trình rõ ràng — ngay trên một màn hình.</p><form class="hero-search-card" action="<?= base_url('locations/index.php') ?>" method="get"><div class="search-field"><span>📍</span><input name="q" placeholder="Bạn muốn đi đâu? Ví dụ: Đà Lạt, Phú Yên..." autocomplete="off"></div><button class="btn btn-primary search-btn">Tìm kiếm</button></form></div></section>
<section class="section-wrap quick-tabs"><div class="row g-2"><div class="col-6 col-lg-3"><a class="tab-card" href="<?= base_url('locations/index.php') ?>"><span class="tab-icon">⌕</span><div><strong>Khám phá</strong><small>Tìm địa điểm phù hợp</small></div></a></div><div class="col-6 col-lg-3"><a class="tab-card" href="<?= $currentUser ? base_url('user/trip-create.php') : base_url('login.php') ?>"><span class="tab-icon">＋</span><div><strong>Tạo chuyến đi</strong><small>Bắt đầu một lịch trình</small></div></a></div><div class="col-6 col-lg-3"><a class="tab-card" href="<?= $currentUser ? base_url('user/trips.php') : base_url('login.php') ?>"><span class="tab-icon">◫</span><div><strong>Chuyến đi của tôi</strong><small>Quản lý mọi kế hoạch</small></div></a></div><div class="col-6 col-lg-3"><a class="tab-card" href="<?= $currentUser ? base_url('user/favorites.php') : '#login-required-modal' ?>" <?= !$currentUser?'data-login-link="1"':'' ?>><span class="tab-icon">♡</span><div><strong>Địa điểm đã lưu</strong><small>Lưu & đồng bộ dữ liệu</small></div></a></div></div></section>
<section class="section-wrap pt-2"><div class="section-head"><div><div class="eyebrow">INSPIRATION</div><h2>Tìm cảm hứng cho chuyến đi tiếp theo</h2></div><a class="section-link" href="<?= base_url('locations/index.php') ?>">Xem tất cả →</a></div><div class="destination-strip"><?php foreach($destinations as $d): ?><a class="destination-chip" href="<?= base_url('locations/index.php?destination_id='.(int)$d['id']) ?>"><img src="<?= e($d['image_url']) ?>" alt="<?= e($d['name']) ?>"><span><?= e($d['name']) ?></span></a><?php endforeach; ?></div></section>
<section class="section-wrap pt-2"><div class="section-head"><div><div class="eyebrow">DISCOVER</div><h2>Địa điểm có thể bạn sẽ thích</h2></div><a class="section-link" href="<?= base_url('locations/index.php') ?>">Xem thêm →</a></div><div class="location-grid">
<?php foreach($featured as $l): $isFav=in_array((int)$l['id'],$favoriteIds,true); ?><article class="location-card"><div class="thumb-wrap"><img src="<?= e($l['image_url']) ?>" alt="<?= e($l['name']) ?>"><button type="button" class="heart-btn js-favorite <?= $isFav?'is-favorite':'' ?>" data-location-id="<?= (int)$l['id'] ?>" aria-label="<?= $isFav?'Bỏ yêu thích':'Thêm yêu thích' ?>" aria-pressed="<?= $isFav?'true':'false' ?>"><?= $isFav?'♥':'♡' ?></button></div><div class="location-body"><span class="pill"><?= e($l['category_name']) ?></span><h3><?= e($l['name']) ?></h3><div class="meta-line">📍 <?= e($l['address']) ?></div><div class="price-row"><span class="rating">★ <?= e($l['display_rating']) ?></span><span class="price"><?= number_format($l['average_cost'],0,',','.') ?>đ/ngày</span></div></div></article><?php endforeach; ?></div></section>
<section class="section-wrap pt-1 pb-5"><div class="promo-banner"><div><h3>Sẵn sàng biến ý tưởng thành lịch trình?</h3><p>Tạo chuyến đi đầu tiên trong vài phút, sau đó để TripMate lo phần sắp xếp.</p></div><div class="d-flex gap-2"><a class="btn btn-light rounded-3" href="<?= $currentUser ? base_url('user/trip-create.php') : base_url('register.php') ?>">Bắt đầu ngay</a><span class="promo-art">✈️</span></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
