<?php
session_start(); require __DIR__.'/../config/database.php'; require __DIR__.'/../includes/helpers.php'; require_admin();
$id=(int)($_GET['id']??0); $st=$pdo->prepare('SELECT * FROM destinations WHERE id=?');$st->execute([$id]);$dest=$st->fetch();if(!$dest){http_response_code(404);exit('Destination not found');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='add_location'){$name=trim($_POST['name']??'');$cat=(int)$_POST['category_id'];$address=trim($_POST['address']??'');$desc=trim($_POST['description']??'');$cost=max(0,(float)$_POST['average_cost']);$rating=max(0,min(5,(float)$_POST['rating']));$img=trim($_POST['image_url']??'');if(!$name||!$address){flash('danger','Vui lòng nhập tên địa danh và địa chỉ.');}else{$pdo->prepare('INSERT INTO locations(destination_id,category_id,name,destination,address,description,average_cost,rating,image_url) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$id,$cat,$name,$dest['name'],$address,$desc,$cost,$rating,$img]);flash('success','Đã thêm địa danh vào '.$dest['name'].'.');}redirect('admin/destination-detail.php?id='.$id);}
 if($action==='delete_location'){$pdo->prepare('DELETE FROM locations WHERE id=? AND destination_id=?')->execute([(int)$_POST['location_id'],$id]);flash('info','Đã xóa địa danh.');redirect('admin/destination-detail.php?id='.$id);}
}
$cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();$st=$pdo->prepare('SELECT l.*,c.name category_name FROM locations l JOIN categories c ON c.id=l.category_id WHERE l.destination_id=? ORDER BY l.id DESC');$st->execute([$id]);$locations=$st->fetchAll();
$pageTitle='Admin · '.$dest['name'];include __DIR__.'/../includes/header.php';show_flash();
?>
<div class="page-shell"><div class="d-flex justify-content-between align-items-start gap-3"><div><a class="small text-decoration-none" href="<?= base_url('admin/destinations.php') ?>">← Tất cả điểm đến</a><div class="eyebrow mt-3">DESTINATION</div><h1 class="page-title mt-1"><?= e($dest['name']) ?></h1><p class="subtext">⭐ <?= e($dest['rating']) ?> · Chi phí dự kiến <?= number_format($dest['average_cost'],0,',','.') ?>đ</p><?php if($dest['notes']): ?><div class="panel mt-3"><strong>Ghi chú</strong><div class="text-secondary mt-1"><?= nl2br(e($dest['notes'])) ?></div></div><?php endif; ?></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#placeModal">+ Thêm địa danh</button></div>
<div class="panel mt-4"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">PLACES</div><h2 class="fw-800 fs-5 mb-0">Địa danh thuộc <?= e($dest['name']) ?></h2></div><span class="pill"><?= count($locations) ?> địa danh</span></div><div class="table-responsive mt-3"><table class="table align-middle"><thead><tr><th>Tên</th><th>Danh mục</th><th>Rating</th><th>Chi phí</th><th></th></tr></thead><tbody><?php foreach($locations as $l): ?><tr><td><strong><?= e($l['name']) ?></strong><div class="small text-secondary"><?= e($l['address']) ?></div></td><td><?= e($l['category_name']) ?></td><td>⭐ <?= e($l['rating']) ?></td><td><?= number_format($l['average_cost'],0,',','.') ?>đ</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?= base_url('admin/locations.php?edit='.$l['id']) ?>">Sửa</a><form method="post" class="d-inline" onsubmit="return confirm('Xóa địa danh này?')"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_location"><input type="hidden" name="location_id" value="<?= $l['id'] ?>"><button class="btn btn-sm btn-link text-danger">Xóa</button></form></td></tr><?php endforeach; ?><?php if(!$locations): ?><tr><td colspan="5" class="text-center text-secondary py-4">Chưa có địa danh. Hãy thêm địa danh đầu tiên.</td></tr><?php endif; ?></tbody></table></div></div></div>
<div class="modal fade" id="placeModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title fw-800">Thêm địa danh — <?= e($dest['name']) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_location"><div class="row g-3"><div class="col-md-8"><label class="form-label">Tên địa danh</label><input class="form-control" name="name" required placeholder="Ví dụ: Hồ Hoàn Kiếm"></div><div class="col-md-4"><label class="form-label">Danh mục</label><select class="form-select" name="category_id"><?php foreach($cats as $c): ?><option value="<?= $c['id'] ?>"><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Địa chỉ</label><input class="form-control" name="address" required></div><div class="col-12"><label class="form-label">Mô tả</label><textarea class="form-control" name="description" rows="3"></textarea></div><div class="col-md-4"><label class="form-label">Chi phí</label><input class="form-control" type="number" min="0" name="average_cost" value="0"></div><div class="col-md-4"><label class="form-label">Rating</label><input class="form-control" type="number" step="0.1" min="0" max="5" name="rating" value="4.5"></div><div class="col-md-4"><label class="form-label">Image URL</label><input class="form-control" name="image_url"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Thêm địa danh</button></div></form></div></div></div>
<?php include __DIR__.'/../includes/footer.php'; ?>
