<?php
session_start();require __DIR__.'/../config/database.php';require __DIR__.'/../includes/helpers.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();$action=$_POST['action']??'';
  if($action==='save'){
    $id=(int)($_POST['id']??0);$destinationId=(int)($_POST['destination_id']??0);$name=trim($_POST['name']??'');$address=trim($_POST['address']??'');$desc=trim($_POST['description']??'');$cost=max(0,(float)($_POST['average_cost']??0));$rating=max(0,min(5,(float)($_POST['rating']??4.5)));$img=trim($_POST['image_url']??'');
    $d=$pdo->prepare('SELECT id,name,is_active FROM destinations WHERE id=?');$d->execute([$destinationId]);$dest=$d->fetch();
    if(!$dest||!(int)$dest['is_active']){flash('danger','Điểm đến không hợp lệ hoặc đang bị ẩn.');redirect('admin/locations.php');}
    if(!$name||!$address){flash('danger','Vui lòng nhập tên địa danh và địa chỉ.');redirect('admin/locations.php');}
    if($id){$pdo->prepare('UPDATE locations SET destination_id=?,destination=?,category_id=?,name=?,address=?,description=?,average_cost=?,rating=?,image_url=? WHERE id=?')->execute([$destinationId,$dest['name'],(int)$_POST['category_id'],$name,$address,$desc,$cost,$rating,$img,$id]);flash('success','Đã cập nhật địa danh.');}
    else{$pdo->prepare('INSERT INTO locations(destination_id,category_id,name,destination,address,description,average_cost,rating,image_url) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$destinationId,(int)$_POST['category_id'],$name,$dest['name'],$address,$desc,$cost,$rating,$img]);flash('success','Đã thêm địa danh.');}
  }elseif($action==='delete'){$pdo->prepare('DELETE FROM locations WHERE id=?')->execute([(int)$_POST['id']]);flash('info','Đã xóa địa danh.');}
  redirect('admin/locations.php');
}
$cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();$destinations=$pdo->query('SELECT id,name FROM destinations WHERE is_active=1 ORDER BY name')->fetchAll();$rows=$pdo->query('SELECT l.*,c.name category_name,d.name destination_name FROM locations l JOIN categories c ON c.id=l.category_id JOIN destinations d ON d.id=l.destination_id ORDER BY d.name,l.id DESC')->fetchAll();
$pageTitle='Admin · Địa danh';include __DIR__.'/../includes/header.php';show_flash();
?>
<div class="page-shell"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">ADMIN</div><h1 class="fw-800 mb-0">Địa danh</h1><div class="subtext mt-1">Mỗi địa danh bắt buộc thuộc một tỉnh / thành phố đã được tạo.</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#locModal" onclick="resetLocationForm()">+ Thêm địa danh</button></div>
<div class="table-responsive mt-4"><table class="table align-middle"><thead><tr><th>Tên địa danh</th><th>Điểm đến</th><th>Danh mục</th><th>Rating</th><th>Cost</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= e($r['name']) ?></strong><div class="small text-secondary"><?= e($r['address']) ?></div></td><td><span class="pill"><?= e($r['destination_name']) ?></span></td><td><?= e($r['category_name']) ?></td><td>⭐ <?= e($r['rating']) ?></td><td><?= number_format($r['average_cost'],0,',','.') ?>đ</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#locModal" onclick='editLocation(<?= json_encode($r,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>)'>Sửa</button><form method="post" class="d-inline" onsubmit="return confirm('Xóa địa danh này?')"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= $r['id'] ?>"><button class="btn btn-sm btn-link text-danger">Xóa</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="modal fade" id="locModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title fw-800" id="locTitle">Thêm địa danh</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="locId"><div class="row g-3"><div class="col-md-7"><label class="form-label">Tên địa danh</label><input class="form-control" name="name" id="locName" required placeholder="Ví dụ: Hồ Hoàn Kiếm"></div><div class="col-md-5"><label class="form-label">Tỉnh / thành phố</label><select class="form-select" name="destination_id" id="locDestination" required><option value="">-- Chọn điểm đến --</option><?php foreach($destinations as $d): ?><option value="<?= $d['id'] ?>"><?= e($d['name']) ?></option><?php endforeach; ?></select><div class="form-text">Không nhập tay để tránh sai tên.</div></div><div class="col-md-4"><label class="form-label">Danh mục</label><select class="form-select" name="category_id" id="locCategory"><?php foreach($cats as $c): ?><option value="<?= $c['id'] ?>"><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Địa chỉ</label><input class="form-control" name="address" id="locAddress" required></div><div class="col-12"><label class="form-label">Mô tả</label><textarea class="form-control" name="description" id="locDescription" rows="3"></textarea></div><div class="col-md-4"><label class="form-label">Chi phí</label><input class="form-control" type="number" min="0" name="average_cost" id="locCost" value="0"></div><div class="col-md-4"><label class="form-label">Rating</label><input class="form-control" type="number" step="0.1" min="0" max="5" name="rating" id="locRating" value="4.5"></div><div class="col-md-4"><label class="form-label">Image URL</label><input class="form-control" name="image_url" id="locImage"></div></div></div><div class="modal-footer"><a class="btn btn-light border" href="<?= base_url('admin/destinations.php') ?>">Quản lý tỉnh/thành</a><button class="btn btn-primary">Lưu địa danh</button></div></form></div></div></div>
<script>function resetLocationForm(){locTitle.textContent='Thêm địa danh';locId.value='';locName.value='';locDestination.value='';locAddress.value='';locDescription.value='';locCost.value='0';locRating.value='4.5';locImage.value='';}function editLocation(r){locTitle.textContent='Sửa địa danh';locId.value=r.id;locName.value=r.name;locDestination.value=r.destination_id;locAddress.value=r.address;locDescription.value=r.description||'';locCost.value=r.average_cost;locRating.value=r.rating;locImage.value=r.image_url||'';}</script>
<?php include __DIR__.'/../includes/footer.php'; ?>
