<?php
session_start(); require __DIR__.'/../config/database.php'; require __DIR__.'/../includes/helpers.php';
$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT l.*,c.name category_name,d.name destination_name FROM locations l JOIN categories c ON c.id=l.category_id JOIN destinations d ON d.id=l.destination_id WHERE l.id=?');$st->execute([$id]);$loc=$st->fetch();if(!$loc){http_response_code(404);exit('Location not found');}
$st=$pdo->prepare('SELECT r.*,u.full_name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.location_id=? ORDER BY r.id DESC LIMIT 10');$st->execute([$id]);$reviews=$st->fetchAll();
$isFav=false;if(!empty($_SESSION['user'])){$st=$pdo->prepare('SELECT id FROM favorites WHERE user_id=? AND location_id=?');$st->execute([$_SESSION['user']['id'],$id]);$isFav=(bool)$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST' && !empty($_SESSION['user'])){verify_csrf();$rating=max(1,min(5,(int)($_POST['rating']??5)));$comment=trim($_POST['comment']??'');if($comment===''){$comment='Đánh giá địa điểm.';} $st=$pdo->prepare('INSERT INTO reviews(user_id,location_id,rating,comment) VALUES(?,?,?,?)');$st->execute([$_SESSION['user']['id'],$id,$rating,$comment]);$avg=$pdo->prepare('SELECT ROUND(AVG(rating),1) FROM reviews WHERE location_id=?');$avg->execute([$id]);$newRating=(float)$avg->fetchColumn();$pdo->prepare('UPDATE locations SET rating=? WHERE id=?')->execute([$newRating,$id]);flash('success','Cảm ơn bạn đã đánh giá.');redirect('locations/detail.php?id='.$id.'#reviews');}
$pageTitle=$loc['name'];include __DIR__.'/../includes/header.php';show_flash();
?>
<div class="container py-5"><div class="row g-5"><div class="col-lg-6"><img class="detail-img" src="<?= e($loc['image_url']) ?>" alt="<?= e($loc['name']) ?>"></div><div class="col-lg-6"><span class="badge-soft"><?= e($loc['category_name']) ?></span><h1 class="fw-800 mt-3"><?= e($loc['name']) ?></h1><p class="text-secondary">📍 <?= e($loc['address']) ?></p><div class="small text-secondary mb-2">Điểm đến: <a href="<?= base_url('locations/index.php?destination_id='.(int)$loc['destination_id']) ?>" class="text-decoration-none"><?= e($loc['destination_name']) ?></a></div><div class="display-6 fw-bold">⭐ <?= e($loc['rating']) ?></div><p class="mt-4 text-secondary"><?= nl2br(e($loc['description'])) ?></p><div class="d-flex gap-2 flex-wrap mt-4"><a class="btn btn-primary" href="<?= base_url('user/trips.php?add_location='.$loc['id']) ?>">+ Thêm vào chuyến đi</a><?php if(!empty($_SESSION['user'])): ?><form method="post" action="<?= base_url('actions/favorite.php') ?>"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="location_id" value="<?= $id ?>"><button class="btn btn-outline-dark"><?= $isFav?'♥ Đã lưu':'♡ Lưu địa điểm' ?></button></form><?php endif; ?></div><div class="info-strip mt-4"><span>Chi phí dự kiến</span><strong><?= number_format($loc['average_cost'],0,',','.') ?>đ</strong></div></div></div>
<section id="reviews" class="mt-5"><div class="d-flex justify-content-between"><h3 class="fw-800">Đánh giá</h3><span class="text-secondary small"><?= count($reviews) ?> đánh giá gần nhất</span></div><?php if(!empty($_SESSION['user'])): ?><div class="panel mt-3 mb-3"><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small fw-semibold">Đánh giá</label><select class="form-select" name="rating"><option value=5>⭐⭐⭐⭐⭐</option><option value=4>⭐⭐⭐⭐</option><option value=3>⭐⭐⭐</option><option value=2>⭐⭐</option><option value=1>⭐</option></select></div><div class="col-md-7"><label class="form-label small fw-semibold">Nhận xét</label><input class="form-control" name="comment" placeholder="Bạn thấy địa điểm này thế nào?" required></div><div class="col-md-2"><button class="btn btn-primary w-100">Gửi</button></div></div></form></div><?php endif; ?><?php foreach($reviews as $r): ?><div class="review-item"><div class="d-flex justify-content-between"><strong><?= e($r['full_name']) ?></strong><span>⭐ <?= e($r['rating']) ?></span></div><div class="small text-secondary mt-1"><?= e($r['comment']) ?></div></div><?php endforeach; ?><?php if(!$reviews): ?><div class="empty-state mt-3">Chưa có đánh giá.</div><?php endif; ?></section></div>
<?php include __DIR__.'/../includes/footer.php'; ?>
