<?php
session_start();require __DIR__.'/../config/database.php';require __DIR__.'/../includes/helpers.php';
$q=trim($_GET['q']??'');$destinationId=(int)($_GET['destination_id']??0);$category=(int)($_GET['category']??0);$sort=$_GET['sort']??'rating';$page=max(1,(int)($_GET['page']??1));$per=8;$params=[];$where=[];
if($q!==''){ $where[]='(l.name LIKE ? OR l.address LIKE ? OR l.description LIKE ? OR d.name LIKE ?)';$like="%$q%";$params=[$like,$like,$like,$like]; }
if($destinationId){$where[]='l.destination_id=?';$params[]=$destinationId;}
if($category){$where[]='l.category_id=?';$params[]=$category;}
$sortMap=['rating'=>'display_rating DESC','name'=>'l.name ASC','cost_asc'=>'l.average_cost ASC','cost_desc'=>'l.average_cost DESC'];$order=$sortMap[$sort]??$sortMap['rating'];$base='FROM locations l JOIN categories c ON c.id=l.category_id JOIN destinations d ON d.id=l.destination_id AND d.is_active=1 LEFT JOIN reviews rv ON rv.location_id=l.id';if($where)$base.=' WHERE '.implode(' AND ',$where);
$st=$pdo->prepare("SELECT COUNT(DISTINCT l.id) $base");$st->execute($params);$total=(int)$st->fetchColumn();$pages=max(1,(int)ceil($total/$per));$offset=($page-1)*$per;$st=$pdo->prepare("SELECT l.*,c.name category_name,d.name destination_name,COALESCE(ROUND(AVG(rv.rating),1),l.rating) AS display_rating $base GROUP BY l.id,c.name,d.name ORDER BY $order LIMIT $per OFFSET $offset");$st->execute($params);$locations=$st->fetchAll();$categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();$destinations=$pdo->query('SELECT id,name FROM destinations WHERE is_active=1 ORDER BY name')->fetchAll();
$favoriteIds=[];if(!empty($_SESSION['user'])){$st=$pdo->prepare('SELECT location_id FROM favorites WHERE user_id=?');$st->execute([(int)$_SESSION['user']['id']]);$favoriteIds=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));}
$selectedDest=null;if($destinationId){$st=$pdo->prepare('SELECT id,name,notes,average_cost,rating,image_url FROM destinations WHERE id=? AND is_active=1');$st->execute([$destinationId]);$selectedDest=$st->fetch();if(!$selectedDest){$destinationId=0;}}
$pageTitle=$selectedDest?$selectedDest['name']:'Khám phá địa điểm';include __DIR__.'/../includes/header.php';show_flash();
?>
<div class="page-shell"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><div class="eyebrow">DESTINATION<?= $selectedDest?' · '.e($selectedDest['name']):'' ?></div><h1 class="page-title"><?= $selectedDest?e($selectedDest['name']):'Tìm nơi đáng đi' ?></h1><div class="subtext"><?= $selectedDest ? 'Các địa danh thuộc điểm đến này.' : 'Tìm theo tên, tỉnh / thành phố, danh mục, rating hoặc chi phí.' ?></div></div><span class="pill"><?= $total ?> địa điểm</span></div>
<?php if($selectedDest): ?><div class="panel mb-4"><div class="row align-items-center g-3"><div class="col-md-3"><img src="<?= e($selectedDest['image_url']) ?>" style="width:100%;height:140px;object-fit:cover;border-radius:12px" alt="<?= e($selectedDest['name']) ?>"></div><div class="col-md-9"><h2 class="fw-800 fs-4 mb-1"><?= e($selectedDest['name']) ?></h2><div class="text-secondary">⭐ <?= e($selectedDest['rating']) ?> · Chi phí dự kiến <?= number_format($selectedDest['average_cost'],0,',','.') ?>đ</div><?php if($selectedDest['notes']): ?><p class="small text-secondary mt-2 mb-0"><?= nl2br(e($selectedDest['notes'])) ?></p><?php endif; ?></div></div></div><?php endif; ?>
<div class="panel mb-4"><form class="row g-2"><div class="col-lg-4"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="🔍 Tìm địa danh..."></div><div class="col-lg-3"><select class="form-select" name="destination_id"><option value="0">Tất cả điểm đến</option><?php foreach($destinations as $d): ?><option value="<?= $d['id'] ?>" <?= $destinationId===(int)$d['id']?'selected':'' ?>><?= e($d['name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><select class="form-select" name="category"><option value="0">Tất cả danh mục</option><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= $category===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><select class="form-select" name="sort"><option value="rating" <?= $sort==='rating'?'selected':'' ?>>Rating cao</option><option value="name" <?= $sort==='name'?'selected':'' ?>>Tên A → Z</option><option value="cost_asc" <?= $sort==='cost_asc'?'selected':'' ?>>Giá thấp</option><option value="cost_desc" <?= $sort==='cost_desc'?'selected':'' ?>>Giá cao</option></select></div><div class="col-lg-1"><button class="btn btn-primary w-100">Tìm</button></div></form></div>
<div class="location-grid"><?php foreach($locations as $l):$isFav=in_array((int)$l['id'],$favoriteIds,true); ?><article class="location-card"><div class="thumb-wrap"><img src="<?= e($l['image_url']) ?>" alt="<?= e($l['name']) ?>"><button type="button" class="heart-btn js-favorite <?= $isFav?'is-favorite':'' ?>" data-location-id="<?= (int)$l['id'] ?>" aria-label="<?= $isFav?'Bỏ yêu thích':'Thêm yêu thích' ?>" aria-pressed="<?= $isFav?'true':'false' ?>"><?= $isFav?'♥':'♡' ?></button></div><div class="location-body"><span class="pill"><?= e($l['category_name']) ?></span><h3><?= e($l['name']) ?></h3><div class="meta-line">📍 <?= e($l['address']) ?></div><div class="small text-secondary mt-1"><?= e($l['destination_name']) ?></div><div class="price-row"><span class="rating">★ <?= e($l['display_rating']) ?></span><span class="price"><?= number_format($l['average_cost'],0,',','.') ?>đ</span></div><a class="btn btn-sm btn-dark w-100 mt-3 rounded-3" href="<?= base_url('locations/detail.php?id='.$l['id']) ?>">Xem chi tiết</a></div></article><?php endforeach; ?></div>
<?php if(!$locations): ?><div class="empty-state mt-4">Điểm đến này chưa có địa danh. Admin có thể thêm địa danh trong trang quản trị.</div><?php endif; ?><?php if($pages>1): ?><nav class="mt-4"><ul class="pagination justify-content-center"><?php for($i=1;$i<=$pages;$i++): ?><li class="page-item <?= $i===$page?'active':'' ?>"><a class="page-link" href="?<?= http_build_query(['q'=>$q,'destination_id'=>$destinationId,'category'=>$category,'sort'=>$sort,'page'=>$i]) ?>"><?= $i ?></a></li><?php endfor; ?></ul></nav><?php endif; ?></div>
<?php include __DIR__.'/../includes/footer.php'; ?>
