<?php
session_start();require __DIR__.'/../config/database.php';require __DIR__.'/../includes/helpers.php';require_login();$uid=$_SESSION['user']['id'];
$q=trim($_GET['q']??'');$params=[];$where=["t.status='published'"];
if($q!==''){ $where[]='(t.name LIKE ? OR t.destination LIKE ?)';$like="%$q%";$params=[$like,$like]; }
$sql='SELECT t.*,u.full_name owner_name,(SELECT COUNT(*) FROM registrations r WHERE r.trip_id=t.id AND r.status<>\'cancelled\') reg_count FROM trips t JOIN users u ON u.id=t.owner_id WHERE '.implode(' AND ',$where).' ORDER BY t.start_date ASC';$st=$pdo->prepare($sql);$st->execute($params);$trips=$st->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$tripId=(int)$_POST['trip_id'];if($tripId){$pdo->prepare('INSERT IGNORE INTO registrations(user_id,trip_id,status) VALUES(?,?,\'pending\')')->execute([$uid,$tripId]);flash('success','Đã gửi đăng ký tham gia chuyến đi.');redirect('user/public-trips.php');}}
$pageTitle='Khám phá chuyến đi';include __DIR__.'/../includes/header.php';show_flash();
?><div class="page-shell"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><div class="eyebrow">COMMUNITY TRIPS</div><h1 class="page-title">Chuyến đi đang mở</h1><div class="subtext">Một lớp demo transaction: đăng ký tham gia chuyến đi đã publish.</div></div><form class="d-flex gap-2"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="Tìm chuyến đi..."><button class="btn btn-primary">Tìm</button></form></div><div class="row g-4"><?php foreach($trips as $t): ?><div class="col-md-6 col-xl-4"><div class="panel h-100"><span class="pill"><?= e($t['destination']) ?></span><h3 class="fs-5 fw-800 mt-3"><?= e($t['name']) ?></h3><div class="subtext"><?= e($t['start_date']) ?> → <?= e($t['end_date']) ?></div><div class="d-flex justify-content-between small mt-4"><span>Người tạo</span><strong><?= e($t['owner_name']) ?></strong></div><div class="d-flex justify-content-between small mt-2"><span>Đã đăng ký</span><strong><?= (int)$t['reg_count'] ?> người</strong></div><div class="d-flex gap-2 mt-4"><form method="post" class="flex-grow-1"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="trip_id" value="<?= $t['id'] ?>"><button class="btn btn-primary w-100 rounded-3">Đăng ký tham gia</button></form><a class="btn btn-light border rounded-3" href="<?= base_url('user/trip-detail.php?id='.$t['id']) ?>">Xem</a></div></div></div><?php endforeach; ?><?php if(!$trips): ?><div class="col-12"><div class="empty-state">Chưa có chuyến đi public. Hãy đổi một trip sang trạng thái published trong Admin hoặc SQL demo.</div></div><?php endif; ?></div></div>
<?php include __DIR__.'/../includes/footer.php'; ?>
