<?php
session_start();require __DIR__.'/../config/database.php';require __DIR__.'/../includes/helpers.php';require_login();$uid=(int)$_SESSION['user']['id'];$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT t.*,u.full_name owner_name FROM trips t JOIN users u ON u.id=t.owner_id WHERE t.id=? AND (t.status='published' OR t.owner_id=? OR EXISTS(SELECT 1 FROM trip_members x WHERE x.trip_id=t.id AND x.user_id=?))");$st->execute([$id,$uid,$uid]);$trip=$st->fetch();if(!$trip){http_response_code(404);exit('Trip not found');}
$st=$pdo->prepare('SELECT i.*,l.name location_name,l.image_url FROM itineraries i LEFT JOIN locations l ON l.id=i.location_id WHERE i.trip_id=? ORDER BY i.day_number,i.start_time');$st->execute([$id]);$items=$st->fetchAll();
$st=$pdo->prepare('SELECT e.*,u.full_name FROM expenses e JOIN users u ON u.id=e.paid_by WHERE e.trip_id=? ORDER BY e.expense_date DESC,e.id DESC');$st->execute([$id]);$expenses=$st->fetchAll();$totalExpense=(float)array_sum(array_map(fn($x)=>(float)$x['amount'],$expenses));
$st=$pdo->prepare('SELECT tm.*,u.full_name,u.email FROM trip_members tm JOIN users u ON u.id=tm.user_id WHERE tm.trip_id=? ORDER BY tm.member_role DESC,u.full_name');$st->execute([$id]);$members=$st->fetchAll();$isOwner=((int)$trip['owner_id']===$uid);$isMember=false;foreach($members as $mm){if((int)$mm['user_id']===$uid){$isMember=true;break;}}
$pdo->exec("CREATE TABLE IF NOT EXISTS checklist_progress (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, checklist_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, is_completed TINYINT(1) NOT NULL DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_checklist_user(checklist_id,user_id), FOREIGN KEY (checklist_id) REFERENCES checklists(id) ON UPDATE CASCADE ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE, INDEX idx_progress_user(user_id,checklist_id)) ENGINE=InnoDB");$pdo->prepare('INSERT IGNORE INTO checklist_progress(checklist_id,user_id) SELECT c.id,? FROM checklists c WHERE c.trip_id=?')->execute([$uid,$id]);$st=$pdo->prepare('SELECT c.*,COALESCE(cp.is_completed,0) AS user_completed FROM checklists c LEFT JOIN checklist_progress cp ON cp.checklist_id=c.id AND cp.user_id=? WHERE c.trip_id=? ORDER BY c.item_order,c.id');$st->execute([$uid,$id]);$checklists=$st->fetchAll();$readinessStmt=$pdo->prepare('SELECT tm.user_id,u.full_name,tm.member_role,COUNT(c.id) AS total_items,COALESCE(SUM(CASE WHEN cp.is_completed=1 THEN 1 ELSE 0 END),0) AS completed_items FROM trip_members tm JOIN users u ON u.id=tm.user_id LEFT JOIN checklists c ON c.trip_id=tm.trip_id LEFT JOIN checklist_progress cp ON cp.checklist_id=c.id AND cp.user_id=tm.user_id WHERE tm.trip_id=? GROUP BY tm.user_id,u.full_name,tm.member_role ORDER BY tm.member_role DESC,u.full_name');$readinessStmt->execute([$id]);$memberReadiness=$readinessStmt->fetchAll();$allReady=!empty($memberReadiness)&&count(array_filter($memberReadiness,fn($m)=>(int)$m['total_items']>0 && (int)$m['completed_items']<(int)$m['total_items']))===0;
$st=$pdo->prepare('SELECT l.* FROM locations l WHERE l.destination_id=? ORDER BY l.rating DESC,l.id DESC LIMIT 30');$st->execute([(int)$trip['destination_id']]);$locations=$st->fetchAll();
$percent=$trip['budget']>0?min(100,round(($totalExpense/$trip['budget'])*100)):0;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='delete_trip' && (int)$trip['owner_id']===$uid){$pdo->prepare('DELETE FROM trips WHERE id=? AND owner_id=?')->execute([$id,$uid]);flash('success','Đã xóa chuyến đi.');redirect('user/trips.php');}
 if($action==='remove_member'){if(!$isOwner){http_response_code(403);exit('Forbidden: bạn không có quyền chỉnh sửa.');}$memberId=(int)$_POST['member_id'];if($memberId===$uid){flash('danger','Không thể xóa chủ chuyến đi.');}else{$pdo->prepare("DELETE FROM trip_members WHERE trip_id=? AND user_id<>? AND user_id=?")->execute([$id,$uid,$memberId]);flash('info','Đã xóa thành viên.');}redirect('user/trip-detail.php?id='.$id.'#members');}
 if($action==='toggle_publish'){$newStatus=($trip['status']==='published'?'draft':'published');$pdo->prepare('UPDATE trips SET status=? WHERE id=? AND owner_id=?')->execute([$newStatus,$id,$uid]);flash('success',$newStatus==='published'?'Đã publish chuyến đi.':'Đã chuyển về bản nháp.');redirect('user/trip-detail.php?id='.$id);}
  if($action==='add_itinerary'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa lịch trình.');}$locationId=(int)($_POST['location_id']??0);$dayNumber=max(1,(int)($_POST['day_number']??1));$startTime=$_POST['start_time']??'';$endTime=$_POST['end_time']??null;$note=trim($_POST['note']??'');$check=$pdo->prepare('SELECT id FROM locations WHERE id=? AND destination_id=?');$check->execute([$locationId,(int)$trip['destination_id']]);if(!$check->fetchColumn()){flash('danger','Địa điểm này không thuộc điểm đến của chuyến đi.');redirect('user/trip-detail.php?id='.$id.'#itinerary');}$pdo->prepare('INSERT INTO itineraries(trip_id,location_id,day_number,start_time,end_time,note) VALUES(?,?,?,?,?,?)')->execute([$id,$locationId,$dayNumber,$startTime,$endTime?:null,$note]);flash('success','Đã thêm lịch trình.');redirect('user/trip-detail.php?id='.$id.'#itinerary');}
  if($action==='delete_itinerary'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa lịch trình.');}$pdo->prepare('DELETE FROM itineraries WHERE id=? AND trip_id=?')->execute([(int)$_POST['item_id'],$id]);flash('info','Đã xóa lịch trình.');redirect('user/trip-detail.php?id='.$id.'#itinerary');}
  if($action==='add_expense'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa ngân sách.');}$amount=(float)($_POST['amount']??0);$expenseDate=$_POST['expense_date']??'';$startDate=$trip['start_date'];$endDate=$trip['end_date'];if($amount<=0){flash('danger','Số tiền phải lớn hơn 0.');redirect('user/trip-detail.php?id='.$id.'#budget');}if($expenseDate<$startDate||$expenseDate>$endDate){flash('danger','Ngày chi phải nằm trong khoảng từ '.date('d/m/Y',strtotime($startDate)).' đến '.date('d/m/Y',strtotime($endDate)).'.');redirect('user/trip-detail.php?id='.$id.'#budget');}$sum=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE trip_id=?');$sum->execute([$id]);$currentTotal=(float)$sum->fetchColumn();if($currentTotal+$amount>(float)$trip['budget']){flash('danger','Không thể thêm khoản chi: tổng chi sẽ vượt ngân sách '.number_format($trip['budget'],0,',','.').'đ.');redirect('user/trip-detail.php?id='.$id.'#budget');}$pdo->prepare('INSERT INTO expenses(trip_id,paid_by,category,amount,description,expense_date) VALUES(?,?,?,?,?,?)')->execute([$id,$uid,trim($_POST['category']),$amount,trim($_POST['description']),$expenseDate]);flash('success','Đã thêm chi phí.');redirect('user/trip-detail.php?id='.$id.'#budget');}
  if($action==='delete_expense'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa ngân sách.');}$pdo->prepare('DELETE FROM expenses WHERE id=? AND trip_id=? AND paid_by=?')->execute([(int)$_POST['expense_id'],$id,$uid]);flash('info','Đã xóa khoản chi.');redirect('user/trip-detail.php?id='.$id.'#budget');}
 if($action==='add_member'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được thêm thành viên.');}$email=trim($_POST['email']??'');$st=$pdo->prepare('SELECT id,full_name FROM users WHERE email=? AND status=\'active\'');$st->execute([$email]);$m=$st->fetch();if(!$m){flash('danger','Không tìm thấy tài khoản hợp lệ.');}elseif((int)$m['id']===$uid){flash('danger','Bạn đã là chủ chuyến đi, không cần thêm chính mình.');}else{$check=$pdo->prepare('SELECT 1 FROM trip_members WHERE trip_id=? AND user_id=?');$check->execute([$id,$m['id']]);if($check->fetchColumn()){flash('info','Tài khoản này đã là thành viên của chuyến đi.');}else{$pdo->prepare('INSERT INTO trip_members(trip_id,user_id,member_role) VALUES(?,?,\'member\')')->execute([$id,$m['id']]);$pdo->prepare('INSERT IGNORE INTO checklist_progress(checklist_id,user_id) SELECT id,? FROM checklists WHERE trip_id=?')->execute([(int)$m['id'],$id]);flash('success','Đã thêm thành viên.');}}redirect('user/trip-detail.php?id='.$id.'#members');}
  if($action==='add_checklist'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa checklist.');}$name=trim($_POST['item_name']??'');if($name){$q=$pdo->prepare('SELECT COALESCE(MAX(item_order)+1,0) FROM checklists WHERE trip_id=?');$q->execute([$id]);$order=(int)$q->fetchColumn();$pdo->prepare('INSERT INTO checklists(trip_id,item_name,is_completed,item_order) VALUES(?,?,0,?)')->execute([$id,$name,$order]);$checklistId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO checklist_progress(checklist_id,user_id) SELECT ?,user_id FROM trip_members WHERE trip_id=?')->execute([$checklistId,$id]);flash('success','Đã thêm checklist.');}redirect('user/trip-detail.php?id='.$id.'#checklist');}
  if($action==='toggle_checklist'){if(!$isMember){http_response_code(403);exit('Forbidden: bạn không phải thành viên của chuyến đi.');}$checklistId=(int)($_POST['item_id']??0);$q=$pdo->prepare('SELECT id FROM checklists WHERE id=? AND trip_id=?');$q->execute([$checklistId,$id]);if(!$q->fetchColumn()){http_response_code(404);exit('Checklist not found');}$pdo->prepare('INSERT INTO checklist_progress(checklist_id,user_id,is_completed) VALUES(?,?,1) ON DUPLICATE KEY UPDATE is_completed=1-is_completed')->execute([$checklistId,$uid]);redirect('user/trip-detail.php?id='.$id.'#checklist');}
  if($action==='delete_checklist'){if(!$isOwner){http_response_code(403);exit('Forbidden: chỉ chủ chuyến đi mới được chỉnh sửa checklist.');}$pdo->prepare('DELETE FROM checklists WHERE id=? AND trip_id=?')->execute([(int)$_POST['item_id'],$id]);flash('info','Đã xóa mục checklist.');redirect('user/trip-detail.php?id='.$id.'#checklist');}
}
$pageTitle=$trip['name'];include __DIR__.'/../includes/header.php';show_flash();
?>
<div class="page-shell">
  <div class="trip-hero">
    <div class="trip-cover"><div class="trip-cover-content"><div class="eyebrow text-white-50"><?= e($trip['destination']) ?></div><h1><?= e($trip['name']) ?></h1><div class="small"><?= e($trip['start_date']) ?> → <?= e($trip['end_date']) ?> · Chủ chuyến đi: <?= e($trip['owner_name']) ?></div><?php if($trip['description']): ?><p class="small mt-3 mb-0" style="max-width:600px"><?= e($trip['description']) ?></p><?php endif; ?></div><div class="trip-actions position-absolute end-0 top-0 m-3 d-flex gap-2">
        <?php if($isOwner): ?><a class="btn btn-light btn-sm rounded-3" href="<?= base_url('user/trip-edit.php?id='.$id) ?>">Chỉnh sửa</a><?php endif; ?>
        <form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="toggle_publish"><button class="btn btn-light btn-sm rounded-3" <?= $trip['owner_id']!=$uid?'disabled':'' ?>><?= $trip['status']==='published'?'● Đang publish':'○ Publish chuyến đi' ?></button></form>
        <?php if($isOwner): ?><form method="post" onsubmit="return confirm('Xóa chuyến đi này?')"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_trip"><button class="btn btn-outline-light btn-sm rounded-3">Xóa</button></form><?php endif; ?></div><div class="trip-stats"><div class="trip-stat"><span>Ngân sách</span><strong><?= number_format($trip['budget'],0,',','.') ?>đ</strong></div><div class="trip-stat"><span>Đã chi</span><strong><?= number_format($totalExpense,0,',','.') ?>đ</strong></div><div class="trip-stat"><span>Lịch trình</span><strong><?= count($items) ?> hoạt động</strong></div><div class="trip-stat"><span>Thành viên</span><strong><?= count($members) ?> người</strong></div></div></div>
    <nav class="trip-tabs"><a class="trip-tab active" href="#itinerary">Lịch trình</a><a class="trip-tab" href="#budget">Ngân sách</a><a class="trip-tab" href="#checklist">Checklist</a><a class="trip-tab" href="#members">Thành viên</a></nav>
  </div>
  <div class="row g-4 mt-1">
    <div class="col-lg-8">
      <section id="itinerary" class="panel"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">DAY BY DAY</div><h2 class="fw-800 fs-4 mb-0">Lịch trình</h2></div><?php if($isOwner): ?><button class="btn btn-primary btn-sm rounded-3" data-bs-toggle="modal" data-bs-target="#itinModal">＋ Thêm hoạt động</button><?php else: ?><span class="badge text-bg-light border">Chỉ chủ chuyến đi chỉnh sửa</span><?php endif; ?></div>
        <div class="mt-4"><?php if(!$items): ?><div class="empty-state">Chưa có hoạt động nào. Hãy thêm một địa điểm phù hợp với <?= e($trip['destination']) ?> để bắt đầu lịch trình.</div><?php else: ?><?php $day=0; ?><div class="timeline"><?php foreach($items as $it): if($day!==$it['day_number']){$day=$it['day_number'];echo '<div class="day-heading mb-3">NGÀY '.$day.'</div>';} ?><div class="timeline-item"><div class="timeline-time"><?= e(substr($it['start_time'],0,5)) ?></div><div class="timeline-dot"></div><div class="timeline-card"><div class="d-flex justify-content-between gap-3"><div><strong><?= e($it['location_name']??'Hoạt động') ?></strong><p><?= e($it['note']) ?></p></div><?php if($isOwner): ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_itinerary"><input type="hidden" name="item_id" value="<?= $it['id'] ?>"><button class="btn btn-sm btn-link text-danger p-0" data-confirm="Xóa hoạt động này?">Xóa</button></form><?php endif; ?></div></div></div><?php endforeach; ?></div><?php endif; ?></div>
      </section>
      <section id="budget" class="panel mt-4"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">BUDGET TRACKER</div><h2 class="fw-800 fs-4 mb-0">Ngân sách</h2></div><?php if($isOwner): ?><button class="btn btn-dark btn-sm rounded-3" data-bs-toggle="modal" data-bs-target="#expenseModal">＋ Thêm khoản chi</button><?php else: ?><span class="badge text-bg-light border">Chỉ chủ chuyến đi chỉnh sửa</span><?php endif; ?></div><div class="row g-3 mt-1"><div class="col-md-4"><div class="mini-stat"><span>Ngân sách</span><strong><?= number_format($trip['budget'],0,',','.') ?>đ</strong></div></div><div class="col-md-4"><div class="mini-stat"><span>Đã chi</span><strong><?= number_format($totalExpense,0,',','.') ?>đ</strong></div></div><div class="col-md-4"><div class="mini-stat"><span>Còn lại</span><strong><?= number_format(max(0,$trip['budget']-$totalExpense),0,',','.') ?>đ</strong></div></div></div><div class="mt-3"><div class="d-flex justify-content-between small mb-1"><span>Tiến độ sử dụng</span><strong><?= $percent ?>%</strong></div><div class="metric-bar"><span style="width:<?= $percent ?>%"></span></div></div><div class="table-responsive mt-3"><table class="table align-middle"><thead><tr><th>Khoản</th><th>Số tiền</th><th>Ngày</th><th></th></tr></thead><tbody><?php foreach($expenses as $ex): ?><tr><td><strong><?= e($ex['category']) ?></strong><div class="text-secondary small"><?= e($ex['description']) ?></div></td><td><?= number_format($ex['amount'],0,',','.') ?>đ</td><td><?= e($ex['expense_date']) ?></td><td><?php if($isOwner): ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_expense"><input type="hidden" name="expense_id" value="<?= $ex['id'] ?>"><button class="btn btn-sm btn-link text-danger p-0" data-confirm="Xóa khoản chi này?">Xóa</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$expenses): ?><tr><td colspan="4" class="text-center text-secondary py-4">Chưa có khoản chi.</td></tr><?php endif; ?></tbody></table></div></section>
      <section class="panel mt-4" id="readiness"><div class="d-flex align-items-start justify-content-between gap-3"><div><div class="eyebrow">TRIP READY</div><h2 class="fw-800 fs-4 mb-1">Tình trạng chuẩn bị của thành viên</h2><div class="small text-secondary">Kiểm tra xem mọi người đã hoàn thành đầy đủ checklist trước chuyến đi chưa.</div></div><span class="pill"><?= $allReady ? '✓ Đã sẵn sàng' : 'Đang chuẩn bị' ?></span></div><div class="mt-3 p-3 rounded-4 border <?= $allReady ? 'bg-light' : 'bg-light' ?>"><div class="fw-semibold mb-2"><?= $allReady ? '🎉 Tất cả thành viên đã chuẩn bị đầy đủ!' : '⚠ Chưa phải tất cả thành viên đã chuẩn bị đầy đủ.' ?></div><div class="small text-secondary"><?= $allReady ? 'Mọi người đã hoàn thành toàn bộ checklist của chuyến đi.' : 'Hãy kiểm tra danh sách dưới đây và nhắc những thành viên còn thiếu.' ?></div></div><div class="mt-3"><?php foreach($memberReadiness as $mr): $total=(int)$mr['total_items']; $done=(int)$mr['completed_items']; $percent=$total>0?(int)round($done*100/$total):0; $ready=$total>0 && $done===$total; ?><div class="member-row"><div class="flex-grow-1"><div class="fw-semibold"><?= e($mr['full_name']) ?> <span class="badge text-bg-light"><?= e($mr['member_role']) ?></span></div><div class="small text-secondary"><?= $total ? $done.' / '.$total.' mục đã chuẩn bị' : 'Chưa có checklist' ?></div></div><div class="text-end"><div class="small fw-semibold"><?= $total ? $percent.'%' : '—' ?></div><span class="badge <?= $ready ? 'text-bg-success' : 'text-bg-warning' ?>"><?= $ready ? 'Đã đủ' : ($total ? 'Chưa đủ' : 'Chưa có') ?></span></div></div><?php endforeach; ?></div></section>
<section id="checklist" class="panel mt-4"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">PREPARE</div><h2 class="fw-800 fs-4 mb-0">Checklist trước chuyến đi</h2><div class="small text-secondary mt-1">Mỗi thành viên tự đánh dấu những việc mình đã chuẩn bị.</div></div><span class="pill"><?= count(array_filter($checklists, fn($c)=>(int)$c['user_completed']===1)) ?>/<?= count($checklists) ?> đã xong</span></div><?php if($isOwner): ?><form method="post" class="input-group mt-3"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_checklist"><input class="form-control" name="item_name" placeholder="Ví dụ: Mang CCCD, sạc dự phòng..." required><button class="btn btn-primary">Thêm</button></form><?php else: ?><div class="alert alert-light border small mt-3 mb-0">Danh sách do chủ chuyến đi tạo. Mỗi thành viên tự đánh dấu phần mình đã chuẩn bị.</div><?php endif; ?><div class="mt-3"><?php if(!$checklists): ?><div class="empty-state">Chưa có việc cần chuẩn bị.</div><?php else: ?><?php foreach($checklists as $c): ?><div class="member-row"><form method="post" class="me-2"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="toggle_checklist"><input type="hidden" name="item_id" value="<?= $c['id'] ?>"><button class="btn btn-sm <?= $c['user_completed']?'btn-success':'btn-outline-secondary' ?>" type="submit"><?= $c['user_completed']?'✓':'○' ?></button></form><div class="flex-grow-1 <?= $c['user_completed']?'text-decoration-line-through text-secondary':'' ?>"><?= e($c['item_name']) ?></div><?php if($isOwner): ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_checklist"><input type="hidden" name="item_id" value="<?= $c['id'] ?>"><button class="btn btn-sm btn-link text-danger p-0">Xóa</button></form><?php endif; ?></div><?php endforeach; ?><?php endif; ?></div></section>
    </div>
    <div class="col-lg-4"><section id="members" class="panel"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">TRAVEL CREW</div><h2 class="fw-800 fs-5 mb-0">Thành viên</h2></div><span class="pill"><?= count($members) ?> người</span></div><?php foreach($members as $m): ?><div class="member-row"><div class="member-avatar">👤</div><div class="flex-grow-1"><strong class="d-block" style="font-size:12px"><?= e($m['full_name']) ?></strong><small class="text-secondary"><?= $m['member_role']==='owner' ? 'owner' : 'member' ?></small></div><?php if($isOwner && (int)$m['user_id']!==$uid): ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="remove_member"><input type="hidden" name="member_id" value="<?= $m['user_id'] ?>"><button class="btn btn-sm btn-link text-danger p-0">Xóa</button></form><?php endif; ?></div><?php endforeach; ?><?php if($isOwner): ?><form method="post" class="mt-3"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_member"><div class="input-group"><input class="form-control" type="email" name="email" placeholder="email@example.com" required><button class="btn btn-dark">Thêm</button></div><small class="text-secondary d-block mt-2">Chỉ chủ chuyến đi mới có quyền thêm thành viên.</small></form><?php else: ?><div class="alert alert-light border small mt-3 mb-0"><strong>Chế độ thành viên:</strong> Bạn chỉ được xem danh sách. Chỉ <strong>chủ chuyến đi</strong> mới có quyền thêm hoặc xóa thành viên.</div><?php endif; ?></section><section class="panel mt-4"><div class="eyebrow">QUICK ADD</div><h2 class="fw-800 fs-5">Gợi ý địa điểm tại <?= e($trip['destination']) ?></h2><?php foreach(array_slice($locations,0,5) as $l): ?><div class="member-row"><img src="<?= e($l['image_url']) ?>" style="width:42px;height:42px;object-fit:cover;border-radius:8px" alt=""><div class="flex-grow-1"><strong class="d-block" style="font-size:12px"><?= e($l['name']) ?></strong><small class="text-secondary">⭐ <?= e($l['rating']) ?> · <?= number_format($l['average_cost'],0,',','.') ?>đ</small></div><?php if($isOwner): ?><button class="btn btn-sm btn-light border" data-bs-toggle="modal" data-bs-target="#itinModal">＋</button><?php endif; ?></div><?php endforeach; ?></section></div>
  </div>
</div>
<?php if($isOwner): ?><div class="modal fade" id="itinModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title fw-800">Thêm hoạt động</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_itinerary"><div class="mb-3"><label class="form-label fw-semibold">Địa điểm hoạt động</label><div class="small text-secondary mb-2">Chỉ hiển thị địa điểm thuộc <strong><?= e($trip['destination']) ?></strong>.</div><select class="form-select" name="location_id"><?php foreach($locations as $l): ?><option value="<?= $l['id'] ?>"><?= e($l['name']) ?></option><?php endforeach; ?></select></div><div class="row g-2"><div class="col-4"><label class="form-label">Ngày</label><input class="form-control" type="number" min="1" max="30" name="day_number" value="1"></div><div class="col-4"><label class="form-label">Bắt đầu</label><input class="form-control" type="time" name="start_time" required></div><div class="col-4"><label class="form-label">Kết thúc</label><input class="form-control" type="time" name="end_time"></div></div><div class="mt-3"><label class="form-label">Ghi chú</label><input class="form-control" name="note" placeholder="Ăn sáng, check-in, nghỉ trưa..."></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu lịch trình</button></div></form></div></div></div>
<?php endif; ?><?php if($isOwner): ?><div class="modal fade" id="expenseModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title fw-800">Thêm khoản chi</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_expense"><div class="mb-3"><label class="form-label fw-semibold">Khoản chi</label><input class="form-control" name="category" placeholder="Khách sạn / Ăn uống / Di chuyển" required></div><div class="mb-3"><label class="form-label fw-semibold">Số tiền</label><input class="form-control" type="number" min="0" step="1000" name="amount" required></div><div class="mb-3"><label class="form-label fw-semibold">Ngày</label><input class="form-control" type="date" name="expense_date" value="<?= max($trip['start_date'],min(date('Y-m-d'),$trip['end_date'])) ?>" min="<?= e($trip['start_date']) ?>" max="<?= e($trip['end_date']) ?>" required></div><div><label class="form-label">Mô tả</label><input class="form-control" name="description"></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu khoản chi</button></div></form></div></div></div><?php endif; ?>
<?php if($isOwner): ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
  const expenseForm = document.querySelector('#expenseModal form');
  if (!expenseForm) return;
  const amountInput = expenseForm.querySelector('[name="amount"]');
  const budget = <?= json_encode((float)$trip['budget']) ?>;
  const spent = <?= json_encode((float)$totalExpense) ?>;
  const remaining = Math.max(0, budget - spent);
  const money = n => new Intl.NumberFormat('vi-VN').format(n) + 'đ';
  const oldAlert = document.getElementById('expenseBudgetAlert');
  if (!oldAlert) {
    const box = document.createElement('div');
    box.id = 'expenseBudgetAlert';
    box.className = 'alert alert-danger d-none mt-3 mb-0';
    amountInput.closest('.mb-3').after(box);
  }
  const alertBox = document.getElementById('expenseBudgetAlert');
  function validateBudget(showMessage) {
    const amount = Number(amountInput.value || 0);
    if (amount > remaining) {
      alertBox.textContent = 'Không thể thêm khoản chi. Bạn chỉ còn ' + money(remaining) + ', nhưng đang nhập ' + money(amount) + '.';
      alertBox.classList.remove('d-none');
      return false;
    }
    alertBox.classList.add('d-none');
    return true;
  }
  amountInput.addEventListener('input', () => validateBudget(false));
  expenseForm.addEventListener('submit', function (e) {
    if (!validateBudget(true)) {
      e.preventDefault();
      amountInput.focus();
    }
  });
});
</script>
<?php endif; ?>
<?php include __DIR__.'/../includes/footer.php'; ?>